spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-ms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password:
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
hs:
  upload:
    path: /upload
    denied: exe,jsp